import { describe, it, expect, beforeEach, afterEach } from "vitest";
import {
  writeToFile,
  generateSummary,
  autogen,
  VIEWS,
  type View,
} from "../src/autogen.js";
import { init } from "../src/core.js";
import { GraphStore } from "../src/graph/store.js";
import type { GraphEdge, GraphNode } from "../src/graph/schema.js";
import {
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
  existsSync,
  mkdirSync,
} from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";

const START = "<!-- engram:start -->";
const END = "<!-- engram:end -->";

const SUMMARY = `${START}\n## Codebase Structure (auto-generated by engram)\n\nfresh content\n${END}`;

describe("writeToFile marker state machine", () => {
  let dir: string;
  let filePath: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), "engram-autogen-"));
    filePath = join(dir, "CLAUDE.md");
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it("state=none: appends to empty file", () => {
    writeToFile(filePath, SUMMARY);
    const result = readFileSync(filePath, "utf-8");
    expect(result).toContain(START);
    expect(result).toContain(END);
    expect(result).toContain("fresh content");
    expect(result.endsWith("\n")).toBe(true);
  });

  it("state=none: appends after existing user content with blank-line separator", () => {
    writeFileSync(filePath, "# My Project\n\nUser-authored intro.\n");
    writeToFile(filePath, SUMMARY);
    const result = readFileSync(filePath, "utf-8");
    // User content preserved
    expect(result).toContain("# My Project");
    expect(result).toContain("User-authored intro.");
    // Summary appended
    expect(result).toContain("fresh content");
    // Blank line separates user content from engram section
    expect(result.indexOf("User-authored intro.\n\n<!--")).toBeGreaterThan(-1);
  });

  it("state=balanced: in-place replacement preserves content ABOVE and BELOW markers", () => {
    const initial = [
      "# My Project",
      "",
      "Header paragraph.",
      "",
      START,
      "## old engram section",
      "stale content",
      END,
      "",
      "## Manual section the user wrote",
      "",
      "Footer paragraph.",
      "",
    ].join("\n");
    writeFileSync(filePath, initial);
    writeToFile(filePath, SUMMARY);
    const result = readFileSync(filePath, "utf-8");
    // Content above markers preserved
    expect(result).toContain("# My Project");
    expect(result).toContain("Header paragraph.");
    // Content below markers preserved — this is the bug we're fixing
    expect(result).toContain("## Manual section the user wrote");
    expect(result).toContain("Footer paragraph.");
    // Old engram content gone
    expect(result).not.toContain("stale content");
    // New engram content present
    expect(result).toContain("fresh content");
    // Exactly one start and one end marker (no duplication)
    expect([...result.matchAll(new RegExp(START, "g"))].length).toBe(1);
    expect([...result.matchAll(new RegExp(END, "g"))].length).toBe(1);
  });

  it("state=unbalanced (two start markers, one end): throws descriptive error", () => {
    const initial = [
      "# Project",
      START,
      "first section",
      START, // duplicate — should trigger unbalanced
      "second section",
      END,
    ].join("\n");
    writeFileSync(filePath, initial);
    expect(() => writeToFile(filePath, SUMMARY)).toThrow(/unbalanced|start marker/i);
    // File must be unchanged (we crash before writing)
    expect(readFileSync(filePath, "utf-8")).toBe(initial);
  });

  it("state=unbalanced (start without end): throws descriptive error", () => {
    const initial = `# Project\n${START}\norphaned content with no end marker\n`;
    writeFileSync(filePath, initial);
    expect(() => writeToFile(filePath, SUMMARY)).toThrow(/marker/i);
    expect(readFileSync(filePath, "utf-8")).toBe(initial);
  });

  it("state=unbalanced (end without start): throws descriptive error", () => {
    const initial = `# Project\nsome content\n${END}\nmore content\n`;
    writeFileSync(filePath, initial);
    expect(() => writeToFile(filePath, SUMMARY)).toThrow(/marker/i);
    expect(readFileSync(filePath, "utf-8")).toBe(initial);
  });

  it("state=fence-nested: markers inside a code fence are NOT treated as real", () => {
    // User is documenting what engram markers look like inside a code block.
    // Those markers should be ignored (fence depth > 0) and the file treated
    // as having no real markers → append normally.
    const initial = [
      "# My Project",
      "",
      "engram uses these markers:",
      "",
      "```markdown",
      START,
      "...engram content...",
      END,
      "```",
      "",
      "That's the convention.",
    ].join("\n");
    writeFileSync(filePath, initial);
    writeToFile(filePath, SUMMARY);
    const result = readFileSync(filePath, "utf-8");
    // Original fenced documentation intact
    expect(result).toContain("```markdown");
    expect(result).toContain("engram uses these markers:");
    expect(result).toContain("That's the convention.");
    // The fenced markers were NOT touched — they still say "...engram content..."
    expect(result).toContain("...engram content...");
    // A new engram section was appended at the end
    expect(result).toContain("fresh content");
    // Should have 2 start markers total (one in fence, one in new appended section)
    expect([...result.matchAll(new RegExp(START, "g"))].length).toBe(2);
  });

  it("state=balanced with fenced markers coexisting: replaces only the real pair", () => {
    const initial = [
      "# Project",
      "",
      "Example of the convention:",
      "",
      "```",
      START,
      "  example inside fence",
      END,
      "```",
      "",
      "Here's the real engram section:",
      "",
      START,
      "old real content",
      END,
      "",
      "Footer.",
    ].join("\n");
    writeFileSync(filePath, initial);
    writeToFile(filePath, SUMMARY);
    const result = readFileSync(filePath, "utf-8");
    // Fenced example preserved
    expect(result).toContain("example inside fence");
    // Footer preserved
    expect(result).toContain("Footer.");
    // Real section replaced
    expect(result).not.toContain("old real content");
    expect(result).toContain("fresh content");
    // The fenced markers stayed, the real markers stayed, and the summary
    // replaced the old real content — so we still have 2 start, 2 end.
    expect([...result.matchAll(new RegExp(START, "g"))].length).toBe(2);
    expect([...result.matchAll(new RegExp(END, "g"))].length).toBe(2);
  });
});

// ─── Phase 2: data-driven Views ─────────────────────────────────────────────
// Helpers to build a store with a known set of nodes/edges for each section
function makeNode(
  id: string,
  label: string,
  kind: GraphNode["kind"],
  metadata: Record<string, unknown> = {}
): GraphNode {
  return {
    id,
    label,
    kind,
    sourceFile: `src/${id}.ts`,
    sourceLocation: null,
    confidence: "EXTRACTED",
    confidenceScore: 1.0,
    lastVerified: Date.now(),
    queryCount: 0,
    metadata,
  };
}

function makeEdge(
  source: string,
  target: string,
  relation: GraphEdge["relation"] = "imports"
): GraphEdge {
  return {
    source,
    target,
    relation,
    confidence: "EXTRACTED",
    confidenceScore: 1.0,
    sourceFile: "x.ts",
    sourceLocation: null,
    lastVerified: Date.now(),
    metadata: {},
  };
}

describe("generateSummary — data-driven Views", () => {
  let dir: string;
  let dbPath: string;
  let store: GraphStore;

  beforeEach(async () => {
    dir = mkdtempSync(join(tmpdir(), "engram-views-"));
    dbPath = join(dir, "graph.db");
    store = await GraphStore.open(dbPath);

    // Seed the store with a richer graph that exercises every section:
    // - 15 function nodes (for god nodes — top 15 max requested by refactor view)
    // - 2 real hot files (git-miner pattern with metadata.type === "hot_file")
    // - 3 real patterns (non-hot-file)
    // - 4 decisions
    // - 3 mistakes
    // - import edges to compute deps

    const nodes: GraphNode[] = [];
    const edges: GraphEdge[] = [];

    for (let i = 0; i < 15; i++) {
      nodes.push(makeNode(`fn${i}`, `func${i}()`, "function"));
    }
    // Create import edges so god nodes get degrees
    for (let i = 0; i < 14; i++) {
      edges.push(makeEdge(`fn${i}`, `fn${i + 1}`));
    }
    // Add more edges on fn0 to make it a super-god
    for (let i = 2; i < 15; i++) edges.push(makeEdge(`fn${i}`, `fn0`));

    // Hot files (git-miner style)
    nodes.push(
      makeNode("hot_a", "🔥 src/a.ts (8 changes)", "pattern", {
        type: "hot_file",
        changeCount: 8,
      }),
      makeNode("hot_b", "🔥 src/b.ts (6 changes)", "pattern", {
        type: "hot_file",
        changeCount: 6,
      })
    );

    // Real patterns (not hot files)
    nodes.push(
      makeNode("pat1", "always use immutable state", "pattern", {}),
      makeNode("pat2", "prefer composition over inheritance", "pattern", {}),
      makeNode("pat3", "pure functions for business logic", "pattern", {})
    );

    // Decisions
    nodes.push(
      makeNode("dec1", "chose JWT for scaling", "decision", {}),
      makeNode("dec2", "picked Postgres over Mongo", "decision", {}),
      makeNode("dec3", "use Vitest not Jest", "decision", {}),
      makeNode("dec4", "go with Fastify", "decision", {})
    );

    // Mistakes
    nodes.push(
      makeNode("mis1", "fs.readFile in event loop caused prod stall", "mistake", {}),
      makeNode("mis2", "forgot to await DB connection", "mistake", {}),
      makeNode("mis3", "nested callbacks in legacy auth", "mistake", {})
    );

    store.bulkUpsert(nodes, edges);
  });

  afterEach(() => {
    store.close();
    rmSync(dir, { recursive: true, force: true });
  });

  it("default view (no argument) equals VIEWS.general", () => {
    const defaultOutput = generateSummary(store);
    const generalOutput = generateSummary(store, VIEWS.general);
    expect(defaultOutput).toBe(generalOutput);
  });

  it("all 4 named views exist and are objects", () => {
    expect(VIEWS.general).toBeDefined();
    expect(VIEWS["bug-fix"]).toBeDefined();
    expect(VIEWS.feature).toBeDefined();
    expect(VIEWS.refactor).toBeDefined();
    for (const v of Object.values(VIEWS)) {
      expect(Array.isArray(v.sections)).toBe(true);
      expect(v.sections.length).toBeGreaterThan(0);
    }
  });

  it("views produce meaningfully different outputs (not just pagination)", () => {
    const general = generateSummary(store, VIEWS.general);
    const bugFix = generateSummary(store, VIEWS["bug-fix"]);
    const feature = generateSummary(store, VIEWS.feature);
    const refactor = generateSummary(store, VIEWS.refactor);

    // Each pair should differ
    expect(bugFix).not.toBe(general);
    expect(feature).not.toBe(general);
    expect(refactor).not.toBe(general);
    expect(bugFix).not.toBe(feature);
    expect(feature).not.toBe(refactor);
  });

  it("bug-fix view has 🔥 Hot files section; general view does not", () => {
    const bugFix = generateSummary(store, VIEWS["bug-fix"]);
    const general = generateSummary(store, VIEWS.general);
    expect(bugFix).toContain("🔥 Hot files");
    expect(general).not.toContain("🔥 Hot files");
  });

  it("bug-fix view omits the Decisions section; feature view emphasizes it", () => {
    const bugFix = generateSummary(store, VIEWS["bug-fix"]);
    const feature = generateSummary(store, VIEWS.feature);
    expect(bugFix).not.toContain("## Decisions");
    expect(feature).toContain("## Decisions");
  });

  it("refactor view lists more god nodes than general view (15 vs 8)", () => {
    const general = generateSummary(store, VIEWS.general);
    const refactor = generateSummary(store, VIEWS.refactor);
    const generalFnCount = (general.match(/func\d+\(\)/g) ?? []).length;
    const refactorFnCount = (refactor.match(/func\d+\(\)/g) ?? []).length;
    expect(refactorFnCount).toBeGreaterThan(generalFnCount);
  });

  it("hot file nodes are NOT included in the Patterns section (filtered by metadata.type)", () => {
    const refactor = generateSummary(store, VIEWS.refactor);
    // Extract the Patterns section only
    const patternsMatch = refactor.match(/## Patterns\n\n([\s\S]*?)(?=\n##|\n<!-- engram:end)/);
    const patternsSection = patternsMatch?.[1] ?? "";
    // Real patterns should be there
    expect(patternsSection).toContain("immutable state");
    // Hot files should NOT appear in patterns section
    expect(patternsSection).not.toContain("🔥");
  });

  it("output always starts with the AUTOGEN_START marker and ends with AUTOGEN_END", () => {
    for (const view of Object.values(VIEWS)) {
      const out = generateSummary(store, view);
      expect(out.startsWith("<!-- engram:start -->")).toBe(true);
      expect(out.trimEnd().endsWith("<!-- engram:end -->")).toBe(true);
    }
  });

  it("empty graph + each view → renders without crashing", async () => {
    const emptyDir = mkdtempSync(join(tmpdir(), "engram-views-empty-"));
    const empty = await GraphStore.open(join(emptyDir, "graph.db"));
    try {
      for (const view of Object.values(VIEWS)) {
        expect(() => generateSummary(empty, view)).not.toThrow();
      }
    } finally {
      empty.close();
      rmSync(emptyDir, { recursive: true, force: true });
    }
  });

  it("custom view with a single section works", () => {
    const minimalView: View = {
      name: "minimal",
      sections: [{ section: "mistakes", limit: 2, heading: "Only mistakes" }],
    };
    const out = generateSummary(store, minimalView);
    expect(out).toContain("Only mistakes");
    expect(out).not.toContain("Core entities");
    expect(out).not.toContain("Decisions");
  });
});

describe("autogen() — task flag", () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = mkdtempSync(join(tmpdir(), "engram-autogen-task-"));
    mkdirSync(join(tmpDir, "src"), { recursive: true });
    writeFileSync(
      join(tmpDir, "src", "index.ts"),
      `export function main() { return 42; }\n`
    );
    await init(tmpDir);
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it("unknown task throws with a descriptive error listing valid keys", async () => {
    await expect(
      autogen(tmpDir, "claude", "bogus-task-name")
    ).rejects.toThrow(/unknown task "bogus-task-name"/);
    await expect(
      autogen(tmpDir, "claude", "bogus-task-name")
    ).rejects.toThrow(/general/);
  });

  it("known task name resolves to the matching view", async () => {
    const result = await autogen(tmpDir, "claude", "bug-fix");
    expect(result.view).toBe("bug-fix");
  });

  it("undefined task defaults to general", async () => {
    const result = await autogen(tmpDir, "claude");
    expect(result.view).toBe("general");
  });
});

describe("autogen() — v3.0 dual-emit (CLAUDE.md + AGENTS.md by default)", () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = mkdtempSync(join(tmpdir(), "engram-autogen-dual-"));
    mkdirSync(join(tmpDir, "src"), { recursive: true });
    writeFileSync(
      join(tmpDir, "src", "index.ts"),
      `export function main() { return 42; }\n`
    );
    await init(tmpDir);
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it("auto target (no flag) emits BOTH CLAUDE.md and AGENTS.md", async () => {
    const result = await autogen(tmpDir);
    expect(result.files).toHaveLength(2);
    expect(result.files).toEqual(
      expect.arrayContaining([
        join(tmpDir, "CLAUDE.md"),
        join(tmpDir, "AGENTS.md"),
      ])
    );
    expect(existsSync(join(tmpDir, "CLAUDE.md"))).toBe(true);
    expect(existsSync(join(tmpDir, "AGENTS.md"))).toBe(true);
  });

  it("auto target also updates legacy .cursorrules if present", async () => {
    writeFileSync(join(tmpDir, ".cursorrules"), "# legacy cursor rules\n");
    const result = await autogen(tmpDir);
    expect(result.files).toHaveLength(3);
    expect(result.files).toEqual(
      expect.arrayContaining([
        join(tmpDir, "CLAUDE.md"),
        join(tmpDir, "AGENTS.md"),
        join(tmpDir, ".cursorrules"),
      ])
    );
  });

  it("explicit --target=claude emits ONLY CLAUDE.md", async () => {
    const result = await autogen(tmpDir, "claude");
    expect(result.files).toEqual([join(tmpDir, "CLAUDE.md")]);
    expect(existsSync(join(tmpDir, "AGENTS.md"))).toBe(false);
  });

  it("explicit --target=agents emits ONLY AGENTS.md", async () => {
    const result = await autogen(tmpDir, "agents");
    expect(result.files).toEqual([join(tmpDir, "AGENTS.md")]);
    expect(existsSync(join(tmpDir, "CLAUDE.md"))).toBe(false);
  });

  it("CLAUDE.md and AGENTS.md contain identical engram-generated content", async () => {
    await autogen(tmpDir);
    const claudeContent = readFileSync(join(tmpDir, "CLAUDE.md"), "utf-8");
    const agentsContent = readFileSync(join(tmpDir, "AGENTS.md"), "utf-8");
    // Both should have the same engram block (single source of truth)
    const claudeBlock = claudeContent.match(/<!-- engram:start -->[\s\S]*<!-- engram:end -->/)?.[0];
    const agentsBlock = agentsContent.match(/<!-- engram:start -->[\s\S]*<!-- engram:end -->/)?.[0];
    expect(claudeBlock).toBeDefined();
    expect(agentsBlock).toBeDefined();
    expect(claudeBlock).toEqual(agentsBlock);
  });
});

