/**
 * Generator for Aider context markdown files.
 * Writes .aider-context.md from the knowledge graph — a snapshot of the most
 * useful context for Aider to load at session start.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";

export interface AiderGenResult {
  readonly filePath: string;
  readonly sections: number;
  readonly nodes: number;
}

const THIRTY_DAYS_MS = 30 * 24 * 60 * 60 * 1000;

/** Build a markdown section or return empty string if no items. */
function buildSection(heading: string, lines: string[]): string {
  if (lines.length === 0) return "";
  return [`## ${heading}`, "", ...lines, ""].join("\n");
}

/**
 * Generate .aider-context.md from the knowledge graph at the given project
 * path. Plain markdown — no YAML frontmatter — so Aider can read it directly.
 */
export async function generateAiderContext(
  projectRoot: string
): Promise<AiderGenResult> {
  const { getStore } = await import("../core.js");
  const store = await getStore(projectRoot);

  try {
    const allNodes = store.getAllNodes();
    const now = Date.now();
    const cutoff = now - THIRTY_DAYS_MS;

    // Architecture section — top 10 god nodes with degree + file
    const godNodes = store.getGodNodes(10);
    const architectureLines = godNodes.map(
      ({ node, degree }) =>
        `- \`${node.label}\` (${node.kind}, ${degree} connections) — ${node.sourceFile}`
    );

    // Hot files — pattern nodes where metadata.type === "hot_file", top 10
    const hotFileLines = allNodes
      .filter(
        (n) =>
          n.kind === "pattern" &&
          (n.metadata as Record<string, unknown>).type === "hot_file"
      )
      .slice(0, 10)
      .map((n) => `- ${n.label}`);

    // Known issues — top 5 mistake nodes by queryCount
    const issueLines = allNodes
      .filter((n) => n.kind === "mistake")
      .sort((a, b) => b.queryCount - a.queryCount)
      .slice(0, 5)
      .map((n) => `- ${n.label}`);

    // Decisions — decision nodes from last 30 days, sorted by lastVerified desc
    const decisionLines = allNodes
      .filter((n) => n.kind === "decision" && n.lastVerified >= cutoff)
      .sort((a, b) => b.lastVerified - a.lastVerified)
      .map((n) => `- ${n.label}`);

    // Key patterns — pattern nodes confidence >= 0.8, not hot_file
    const patternLines = allNodes
      .filter(
        (n) =>
          n.kind === "pattern" &&
          n.confidenceScore >= 0.8 &&
          (n.metadata as Record<string, unknown>).type !== "hot_file"
      )
      .map((n) => `- ${n.label}`);

    const sections = [
      buildSection("Architecture", architectureLines),
      buildSection("Hot Files", hotFileLines),
      buildSection("Known Issues", issueLines),
      buildSection("Decisions", decisionLines),
      buildSection("Key Patterns", patternLines),
    ].filter((s) => s.length > 0);

    const header = [
      "# engram context",
      "",
      "> Auto-generated by engram. Do not edit manually.",
      "> Regenerate: `engram gen-aider -p .`",
      "",
    ].join("\n");

    const content = header + sections.join("\n");

    const outPath = join(projectRoot, ".aider-context.md");
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, content, "utf-8");

    const nodeCount =
      architectureLines.length +
      hotFileLines.length +
      issueLines.length +
      decisionLines.length +
      patternLines.length;

    return { filePath: outPath, sections: sections.length, nodes: nodeCount };
  } finally {
    store.close();
  }
}
