/**
 * Generator for Windsurf (Codeium) `.windsurfrules` files.
 *
 * Writes a plain-markdown file at the project root that Windsurf's
 * AI picks up automatically for every chat session — same pattern as
 * Cursor's `.cursorrules`, but with Windsurf's filename convention.
 *
 * Content is a distilled snapshot of the knowledge graph: architecture
 * (god nodes), active decisions, known landmines, key patterns, and
 * hot files. Regenerate with `engram gen-windsurfrules --watch` to keep
 * the file in sync with graph changes.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";

export interface WindsurfGenResult {
  readonly filePath: string;
  readonly sections: number;
  readonly nodes: number;
}

const THIRTY_DAYS_MS = 30 * 24 * 60 * 60 * 1000;

/** Build a markdown section or return empty string if no items. */
function buildSection(heading: string, lines: string[]): string {
  if (lines.length === 0) return "";
  return [`## ${heading}`, "", ...lines, ""].join("\n");
}

/**
 * Generate `.windsurfrules` at the project root from the knowledge graph.
 * Plain markdown — Windsurf loads it automatically when opening a workspace.
 */
export async function generateWindsurfRules(
  projectRoot: string
): Promise<WindsurfGenResult> {
  const { getStore } = await import("../core.js");
  const store = await getStore(projectRoot);

  try {
    const allNodes = store.getAllNodes();
    const now = Date.now();
    const cutoff = now - THIRTY_DAYS_MS;

    // Architecture — top 10 god nodes with degree + file path
    const godNodes = store.getGodNodes(10);
    const architectureLines = godNodes.map(
      ({ node, degree }) =>
        `- \`${node.label}\` (${node.kind}, ${degree} connections) — ${node.sourceFile}`
    );

    // Hot files — pattern nodes where metadata.type === "hot_file", top 10
    const hotFileLines = allNodes
      .filter(
        (n) =>
          n.kind === "pattern" &&
          (n.metadata as Record<string, unknown>).type === "hot_file"
      )
      .slice(0, 10)
      .map((n) => `- ${n.label}`);

    // Known landmines — top 5 mistake nodes by queryCount
    const mistakeLines = allNodes
      .filter((n) => n.kind === "mistake")
      .sort((a, b) => b.queryCount - a.queryCount)
      .slice(0, 5)
      .map((n) => `- ${n.label}`);

    // Active decisions — last 30 days, sorted by lastVerified desc
    const decisionLines = allNodes
      .filter((n) => n.kind === "decision" && n.lastVerified >= cutoff)
      .sort((a, b) => b.lastVerified - a.lastVerified)
      .map((n) => `- ${n.label}`);

    // Key patterns — pattern nodes with confidence >= 0.8, excluding hot_file
    const patternLines = allNodes
      .filter(
        (n) =>
          n.kind === "pattern" &&
          n.confidenceScore >= 0.8 &&
          (n.metadata as Record<string, unknown>).type !== "hot_file"
      )
      .map((n) => `- ${n.label}`);

    const sections = [
      buildSection("Architecture", architectureLines),
      buildSection("Known Landmines", mistakeLines),
      buildSection("Active Decisions", decisionLines),
      buildSection("Key Patterns", patternLines),
      buildSection("Hot Files", hotFileLines),
    ].filter((s) => s.length > 0);

    const header = [
      "# engram context",
      "",
      "> Auto-generated by engram. Do not edit manually.",
      "> Regenerate: `engram gen-windsurfrules -p .`",
      "> Prefer `engram query \"...\"` for structural queries — this file is a snapshot.",
      "",
    ].join("\n");

    const content = header + sections.join("\n");

    const outPath = join(projectRoot, ".windsurfrules");
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, content, "utf-8");

    const nodeCount =
      architectureLines.length +
      hotFileLines.length +
      mistakeLines.length +
      decisionLines.length +
      patternLines.length;

    return {
      filePath: outPath,
      sections: sections.length,
      nodes: nodeCount,
    };
  } finally {
    store.close();
  }
}
