/**
 * CCS exporter — writes KG nodes as a CCS-format .context/index.md.
 * Exports pattern, decision, mistake, and high-traffic concept nodes.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import type { GraphNode } from "../graph/schema.js";

export interface CcsExportResult {
  readonly filePath: string;
  readonly sectionsWritten: number;
  readonly nodesExported: number;
}

const CCS_FILE = join(".context", "index.md");

const HEADER =
  "# Project Context\n\n" +
  "> Auto-generated by engram. See https://github.com/Agentic-Insights/codebase-context-spec\n";

function bullet(label: string): string {
  return `- ${label}`;
}

function buildSection(heading: string, nodes: GraphNode[]): string {
  if (nodes.length === 0) return "";
  const bullets = nodes.map((n) => bullet(n.label));
  return [`## ${heading}`, "", ...bullets, ""].join("\n");
}

export async function exportCcs(projectRoot: string): Promise<CcsExportResult> {
  const { getStore } = await import("../core.js");
  const store = await getStore(projectRoot);

  try {
    const allNodes = store.getAllNodes();

    // Architecture Patterns — pattern nodes with confidence >= 0.8, by queryCount
    const patternNodes = allNodes
      .filter(
        (n) =>
          n.kind === "pattern" &&
          n.confidenceScore >= 0.8 &&
          (n.metadata as Record<string, unknown>).type !== "hot_file"
      )
      .sort((a, b) => b.queryCount - a.queryCount);

    // Decisions — all decision nodes, newest first
    const decisionNodes = allNodes
      .filter((n) => n.kind === "decision")
      .sort((a, b) => b.lastVerified - a.lastVerified);

    // Known Issues — mistake nodes by queryCount (most-hit first)
    const mistakeNodes = allNodes
      .filter((n) => n.kind === "mistake")
      .sort((a, b) => b.queryCount - a.queryCount);

    // Key Concepts — concept nodes with queryCount > 0, top 10
    const conceptNodes = allNodes
      .filter((n) => n.kind === "concept" && n.queryCount > 0)
      .sort((a, b) => b.queryCount - a.queryCount)
      .slice(0, 10);

    const sections = [
      buildSection("Architecture Patterns", patternNodes),
      buildSection("Decisions", decisionNodes),
      buildSection("Known Issues", mistakeNodes),
      buildSection("Key Concepts", conceptNodes),
    ].filter((s) => s.length > 0);

    const content = [HEADER, ...sections].join("\n");

    const outPath = join(projectRoot, CCS_FILE);
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, content, "utf-8");

    const nodesExported =
      patternNodes.length +
      decisionNodes.length +
      mistakeNodes.length +
      conceptNodes.length;

    return {
      filePath: outPath,
      sectionsWritten: sections.length,
      nodesExported,
    };
  } finally {
    store.close();
  }
}
