import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdirSync, existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { init } from "../../src/core.js";
import { generateWindsurfRules } from "../../src/generators/windsurf-rules.js";

describe("generateWindsurfRules", () => {
  let testDir: string;

  beforeEach(async () => {
    testDir = join(tmpdir(), `engram-windsurf-${Date.now()}`);
    mkdirSync(join(testDir, "src"), { recursive: true });
    writeFileSync(
      join(testDir, "src", "app.ts"),
      `export class AuthService {
  login() { return true; }
  logout() { return false; }
}

export function createAuthService(): AuthService {
  return new AuthService();
}
`
    );
    await init(testDir);
  });

  afterEach(() => {
    rmSync(testDir, { recursive: true, force: true });
  });

  it("creates .windsurfrules in project root", async () => {
    const result = await generateWindsurfRules(testDir);
    expect(result.filePath).toBe(join(testDir, ".windsurfrules"));
    expect(existsSync(result.filePath)).toBe(true);
  });

  it("writes valid markdown with engram header", async () => {
    const result = await generateWindsurfRules(testDir);
    const content = readFileSync(result.filePath, "utf-8");
    expect(content).toContain("# engram context");
    expect(content).toContain("Auto-generated by engram");
    expect(content).toContain("Regenerate: `engram gen-windsurfrules -p .`");
  });

  it("returns section + node counts", async () => {
    const result = await generateWindsurfRules(testDir);
    expect(result.sections).toBeGreaterThan(0);
    expect(result.nodes).toBeGreaterThan(0);
  });

  it("includes Architecture section when god nodes exist", async () => {
    const result = await generateWindsurfRules(testDir);
    const content = readFileSync(result.filePath, "utf-8");
    // Small project may not produce god nodes — check that *some* expected
    // section header is present
    const hasAnySection =
      content.includes("## Architecture") ||
      content.includes("## Known Landmines") ||
      content.includes("## Active Decisions") ||
      content.includes("## Key Patterns") ||
      content.includes("## Hot Files");
    expect(hasAnySection).toBe(true);
  });

  it("is idempotent — regenerating produces the same file", async () => {
    const first = await generateWindsurfRules(testDir);
    const firstContent = readFileSync(first.filePath, "utf-8");
    const second = await generateWindsurfRules(testDir);
    const secondContent = readFileSync(second.filePath, "utf-8");
    expect(secondContent).toBe(firstContent);
  });

  it("does not include YAML frontmatter (plain markdown)", async () => {
    const result = await generateWindsurfRules(testDir);
    const content = readFileSync(result.filePath, "utf-8");
    // First line should be `# engram context`, not `---`
    expect(content.startsWith("# engram context")).toBe(true);
    expect(content.startsWith("---")).toBe(false);
  });
});
